version: '3.8'

services:
  app:
    image: kunigami21/arialmed:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PROJECT_ID=${PROJECT_ID}
      - API_KEY=${API_KEY}
